create table gva.jyx_user (
                              id bigint unsigned auto_increment primary key comment '表主键',
                              name varchar(64)  comment '姓名',
                              IDType varchar(64) comment '证件类型',
                              UID varchar(64) comment '身份证号' ,
                              sex varchar(64) comment '性别',
                              dateBirth varchar(64) comment '出生日期',
                              eduLevel varchar(64) comment '文化程度',
                              source varchar(64) comment '考生来源',
                              receive varchar(64) comment '证件领取',
                              professionalName varchar(64) comment '职业名称',
                              workType varchar(64) comment '工种名称',
                              level varchar(64) comment '级别',
                              conditions varchar(64) comment '申报条件',
                              phone varchar(64) comment '手机号',
                              workDate varchar(64) comment '参加工作时间',
                              work varchar(64) comment '从事专业',
                              workYear varchar(64) comment '专业年限',
                              nation varchar(64) comment '民族',
                              politicalStatus varchar(64) comment '政治面貌',
                              serialNumber varchar(64) comment '学历证书编号',
                              experience text comment '简要经历',
                              postalCode varchar(64) comment '邮政编码',
                              currentUnit varchar(64) comment '所在单位',
                              address varchar(256) comment '通讯地址',
                              postAddress varchar(256) comment '邮寄地址',
                              email varchar(64) comment '邮箱',
                              place varchar(256) comment '户籍所在地',
                              province varchar(64) comment '省份',
                              city varchar(64) comment '城市',
                              OCO varchar(64) comment '原证书职业',
                              OCL varchar(64) comment '原证书等级',
                              OCN varchar(64) comment '原证书编号',
                              userPic varchar(600) comment '用户照片',
                              userCertify varchar(600) comment '学籍在线证明或工作证明',
                              userPay varchar(600) comment '支付凭证',
                              isPay varchar(10) comment '已支付|未支付',
                              payAmount varchar(30) comment '支付金额'
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

alter table gva.jyx_user add verify int default 99 comment '1:审核通过|2：未通过' after payAmount;
alter table gva.jyx_user add verify_reason text comment '审核备注' after verify;